# Generated by Django 4.2.16 on 2026-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='bounding_boxes',
            field=models.JSONField(blank=True, help_text="Stores array of bounding boxes: [{'label':'x','x':0,'y':0,'w':0,'h':0}]", null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
